spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatpr?useUnicode=true&characterEncoding=utf8
    username: root
    password: ALStn840!
 #JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true

    
    

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: aA12345!!

    
  # JPA
#  jpa:
#    # database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
#    defer-datasource-initialization: true


server:
  port: 8888 
  
  